{"url":"https://api.github.com/repos/philipperemy/keras-tcn/issues/24","repository_url":"https://api.github.com/repos/philipperemy/keras-tcn","labels_url":"https://api.github.com/repos/philipperemy/keras-tcn/issues/24/labels{/name}","comments_url":"https://api.github.com/repos/philipperemy/keras-tcn/issues/24/comments","events_url":"https://api.github.com/repos/philipperemy/keras-tcn/issues/24/events","html_url":"https://github.com/philipperemy/keras-tcn/issues/24","id":379742582,"node_id":"MDU6SXNzdWUzNzk3NDI1ODI=","number":24,"title":"Keras installation error","user":{"login":"Rasipuram","id":26164322,"node_id":"MDQ6VXNlcjI2MTY0MzIy","avatar_url":"https://avatars.githubusercontent.com/u/26164322?v=4","gravatar_id":"","url":"https://api.github.com/users/Rasipuram","html_url":"https://github.com/Rasipuram","followers_url":"https://api.github.com/users/Rasipuram/followers","following_url":"https://api.github.com/users/Rasipuram/following{/other_user}","gists_url":"https://api.github.com/users/Rasipuram/gists{/gist_id}","starred_url":"https://api.github.com/users/Rasipuram/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/Rasipuram/subscriptions","organizations_url":"https://api.github.com/users/Rasipuram/orgs","repos_url":"https://api.github.com/users/Rasipuram/repos","events_url":"https://api.github.com/users/Rasipuram/events{/privacy}","received_events_url":"https://api.github.com/users/Rasipuram/received_events","type":"User","site_admin":false},"labels":[{"id":875498559,"node_id":"MDU6TGFiZWw4NzU0OTg1NTk=","url":"https://api.github.com/repos/philipperemy/keras-tcn/labels/question","name":"question","color":"d876e3","default":true,"description":"Further information is requested"}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":15,"created_at":"2018-11-12T11:51:10Z","updated_at":"2019-06-21T01:45:00Z","closed_at":"2018-11-15T01:33:46Z","author_association":"NONE","active_lock_reason":null,"body":"I could install tcn using pip install keras-tcn successfully without any error.\r\nBut when I use it as\r\n\"from tcn import tcn\" the following error gets generated.\r\nFile \"/Users/sowmyar/anaconda/lib/python2.7/site-packages/tcn/tcn.py\", line 95\r\n    print(f'Updated dilations from {dilations} to {new_dilations} because of backwards compatibility.')\r\n                                                                                                     ^\r\nSyntaxError: invalid syntax\r\n\r\nCan you help me with this issue?\r\n","closed_by":{"login":"philipperemy","id":4516927,"node_id":"MDQ6VXNlcjQ1MTY5Mjc=","avatar_url":"https://avatars.githubusercontent.com/u/4516927?v=4","gravatar_id":"","url":"https://api.github.com/users/philipperemy","html_url":"https://github.com/philipperemy","followers_url":"https://api.github.com/users/philipperemy/followers","following_url":"https://api.github.com/users/philipperemy/following{/other_user}","gists_url":"https://api.github.com/users/philipperemy/gists{/gist_id}","starred_url":"https://api.github.com/users/philipperemy/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/philipperemy/subscriptions","organizations_url":"https://api.github.com/users/philipperemy/orgs","repos_url":"https://api.github.com/users/philipperemy/repos","events_url":"https://api.github.com/users/philipperemy/events{/privacy}","received_events_url":"https://api.github.com/users/philipperemy/received_events","type":"User","site_admin":false},"reactions":{"url":"https://api.github.com/repos/philipperemy/keras-tcn/issues/24/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/philipperemy/keras-tcn/issues/24/timeline","performed_via_github_app":null,"state_reason":"completed"}