{"url":"https://api.github.com/repos/DrSleep/light-weight-refinenet/issues/41","repository_url":"https://api.github.com/repos/DrSleep/light-weight-refinenet","labels_url":"https://api.github.com/repos/DrSleep/light-weight-refinenet/issues/41/labels{/name}","comments_url":"https://api.github.com/repos/DrSleep/light-weight-refinenet/issues/41/comments","events_url":"https://api.github.com/repos/DrSleep/light-weight-refinenet/issues/41/events","html_url":"https://github.com/DrSleep/light-weight-refinenet/issues/41","id":450658415,"node_id":"MDU6SXNzdWU0NTA2NTg0MTU=","number":41,"title":"About RuntimeErrorï¼šCUDA out of memory","user":{"login":"Txrachel","id":50823484,"node_id":"MDQ6VXNlcjUwODIzNDg0","avatar_url":"https://avatars.githubusercontent.com/u/50823484?v=4","gravatar_id":"","url":"https://api.github.com/users/Txrachel","html_url":"https://github.com/Txrachel","followers_url":"https://api.github.com/users/Txrachel/followers","following_url":"https://api.github.com/users/Txrachel/following{/other_user}","gists_url":"https://api.github.com/users/Txrachel/gists{/gist_id}","starred_url":"https://api.github.com/users/Txrachel/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/Txrachel/subscriptions","organizations_url":"https://api.github.com/users/Txrachel/orgs","repos_url":"https://api.github.com/users/Txrachel/repos","events_url":"https://api.github.com/users/Txrachel/events{/privacy}","received_events_url":"https://api.github.com/users/Txrachel/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":4,"created_at":"2019-05-31T07:34:56Z","updated_at":"2019-08-11T17:53:55Z","closed_at":"2019-08-11T17:53:55Z","author_association":"NONE","active_lock_reason":null,"body":"Hi,\r\nThanks for your wonderful work and detailed tutorial.\r\nI am just a fresh new here, when I try to retrain the model, there will be RuntimeError. Then I set the Batch_Size (config.py) to [1] * 3, it also can't work. I wonder if you have ever met this problem? \r\nCould you please help me? \r\nThanks in advance!\r\n\r\nINFO:__main__: Train epoch: 0 [0/795]\tAvg. Loss: 3.751\tAvg. Time: 1.046\r\nTraceback (most recent call last):\r\n  File \"src/train.py\", line 425, in <module>\r\n    main()\r\n  File \"src/train.py\", line 409, in main\r\n    args.freeze_bn[task_idx])\r\n  File \"src/train.py\", line 273, in train_segmenter\r\n    output = segmenter(input_var)\r\n  File \"/home/txr/.virtualenvs/env_test/lib/python3.5/site-packages/torch/nn/modules/module.py\", line 493, in __call__\r\n    result = self.forward(*input, **kwargs)\r\n  File \"/home/txr/.virtualenvs/env_test/lib/python3.5/site-packages/torch/nn/parallel/data_parallel.py\", line 150, in forward\r\n    return self.module(*inputs[0], **kwargs[0])\r\n  File \"/home/txr/.virtualenvs/env_test/lib/python3.5/site-packages/torch/nn/modules/module.py\", line 493, in __call__\r\n    result = self.forward(*input, **kwargs)\r\n  File \"/home/txr/SS/light-weight-refinenet/models/resnet.py\", line 237, in forward\r\n    x1 = self.mflow_conv_g4_pool(x1)\r\n  File \"/home/txr/.virtualenvs/env_test/lib/python3.5/site-packages/torch/nn/modules/module.py\", line 493, in __call__\r\n    result = self.forward(*input, **kwargs)\r\n  File \"/home/txr/.virtualenvs/env_test/lib/python3.5/site-packages/torch/nn/modules/container.py\", line 92, in forward\r\n    input = module(input)\r\n  File \"/home/txr/.virtualenvs/env_test/lib/python3.5/site-packages/torch/nn/modules/module.py\", line 493, in __call__\r\n    result = self.forward(*input, **kwargs)\r\n  File \"/home/txr/SS/light-weight-refinenet/utils/layer_factory.py\", line 72, in forward\r\n    top = self.maxpool(top)\r\n  File \"/home/txr/.virtualenvs/env_test/lib/python3.5/site-packages/torch/nn/modules/module.py\", line 493, in __call__\r\n    result = self.forward(*input, **kwargs)\r\n  File \"/home/txr/.virtualenvs/env_test/lib/python3.5/site-packages/torch/nn/modules/pooling.py\", line 146, in forward\r\n    self.return_indices)\r\n  File \"/home/txr/.virtualenvs/env_test/lib/python3.5/site-packages/torch/_jit_internal.py\", line 133, in fn\r\n    return if_false(*args, **kwargs)\r\n  File \"/home/txr/.virtualenvs/env_test/lib/python3.5/site-packages/torch/nn/functional.py\", line 494, in _max_pool2d\r\n    input, kernel_size, stride, padding, dilation, ceil_mode)\r\nRuntimeError: CUDA out of memory. Tried to allocate 32.00 MiB (GPU 0; 1.96 GiB total capacity; 1.14 GiB already allocated; 20.06 MiB free; 41.52 MiB cached)\r\n","closed_by":{"login":"DrSleep","id":7841432,"node_id":"MDQ6VXNlcjc4NDE0MzI=","avatar_url":"https://avatars.githubusercontent.com/u/7841432?v=4","gravatar_id":"","url":"https://api.github.com/users/DrSleep","html_url":"https://github.com/DrSleep","followers_url":"https://api.github.com/users/DrSleep/followers","following_url":"https://api.github.com/users/DrSleep/following{/other_user}","gists_url":"https://api.github.com/users/DrSleep/gists{/gist_id}","starred_url":"https://api.github.com/users/DrSleep/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/DrSleep/subscriptions","organizations_url":"https://api.github.com/users/DrSleep/orgs","repos_url":"https://api.github.com/users/DrSleep/repos","events_url":"https://api.github.com/users/DrSleep/events{/privacy}","received_events_url":"https://api.github.com/users/DrSleep/received_events","type":"User","site_admin":false},"reactions":{"url":"https://api.github.com/repos/DrSleep/light-weight-refinenet/issues/41/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/DrSleep/light-weight-refinenet/issues/41/timeline","performed_via_github_app":null,"state_reason":"completed"}