{"url":"https://api.github.com/repos/vgrabovets/multi_rake/issues/37","repository_url":"https://api.github.com/repos/vgrabovets/multi_rake","labels_url":"https://api.github.com/repos/vgrabovets/multi_rake/issues/37/labels{/name}","comments_url":"https://api.github.com/repos/vgrabovets/multi_rake/issues/37/comments","events_url":"https://api.github.com/repos/vgrabovets/multi_rake/issues/37/events","html_url":"https://github.com/vgrabovets/multi_rake/issues/37","id":745774791,"node_id":"MDU6SXNzdWU3NDU3NzQ3OTE=","number":37,"title":"Muli-rake installation failed","user":{"login":"MariamRiaz","id":44466300,"node_id":"MDQ6VXNlcjQ0NDY2MzAw","avatar_url":"https://avatars.githubusercontent.com/u/44466300?v=4","gravatar_id":"","url":"https://api.github.com/users/MariamRiaz","html_url":"https://github.com/MariamRiaz","followers_url":"https://api.github.com/users/MariamRiaz/followers","following_url":"https://api.github.com/users/MariamRiaz/following{/other_user}","gists_url":"https://api.github.com/users/MariamRiaz/gists{/gist_id}","starred_url":"https://api.github.com/users/MariamRiaz/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/MariamRiaz/subscriptions","organizations_url":"https://api.github.com/users/MariamRiaz/orgs","repos_url":"https://api.github.com/users/MariamRiaz/repos","events_url":"https://api.github.com/users/MariamRiaz/events{/privacy}","received_events_url":"https://api.github.com/users/MariamRiaz/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":4,"created_at":"2020-11-18T15:47:08Z","updated_at":"2021-06-25T06:12:52Z","closed_at":"2021-06-25T06:11:59Z","author_association":"NONE","active_lock_reason":null,"body":"I am trying to use multirake in a google colab notebook. i keep on getting this error \r\nsing cached https://files.pythonhosted.org/packages/52/6d/044789e730141bcda2a7368836f714684a7d13bd44a2a33b387cb31b4335/cld2-cffi-0.1.4.tar.gz\r\nERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\r\n\r\ni tried installing pip install cld2-cffi and it gives the error \r\ncollecting cld2-cffi\r\n  Using cached https://files.pythonhosted.org/packages/52/6d/044789e730141bcda2a7368836f714684a7d13bd44a2a33b387cb31b4335/cld2-cffi-0.1.4.tar.gz\r\nERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.","closed_by":{"login":"vgrabovets","id":22475959,"node_id":"MDQ6VXNlcjIyNDc1OTU5","avatar_url":"https://avatars.githubusercontent.com/u/22475959?v=4","gravatar_id":"","url":"https://api.github.com/users/vgrabovets","html_url":"https://github.com/vgrabovets","followers_url":"https://api.github.com/users/vgrabovets/followers","following_url":"https://api.github.com/users/vgrabovets/following{/other_user}","gists_url":"https://api.github.com/users/vgrabovets/gists{/gist_id}","starred_url":"https://api.github.com/users/vgrabovets/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/vgrabovets/subscriptions","organizations_url":"https://api.github.com/users/vgrabovets/orgs","repos_url":"https://api.github.com/users/vgrabovets/repos","events_url":"https://api.github.com/users/vgrabovets/events{/privacy}","received_events_url":"https://api.github.com/users/vgrabovets/received_events","type":"User","site_admin":false},"reactions":{"url":"https://api.github.com/repos/vgrabovets/multi_rake/issues/37/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/vgrabovets/multi_rake/issues/37/timeline","performed_via_github_app":null,"state_reason":"completed"}