{"url":"https://api.github.com/repos/ahmedbesbes/character-based-cnn/issues/2","repository_url":"https://api.github.com/repos/ahmedbesbes/character-based-cnn","labels_url":"https://api.github.com/repos/ahmedbesbes/character-based-cnn/issues/2/labels{/name}","comments_url":"https://api.github.com/repos/ahmedbesbes/character-based-cnn/issues/2/comments","events_url":"https://api.github.com/repos/ahmedbesbes/character-based-cnn/issues/2/events","html_url":"https://github.com/ahmedbesbes/character-based-cnn/issues/2","id":470701731,"node_id":"MDU6SXNzdWU0NzA3MDE3MzE=","number":2,"title":"Model trained on GPU is unable to predict on CPU","user":{"login":"desmondlzy","id":38628974,"node_id":"MDQ6VXNlcjM4NjI4OTc0","avatar_url":"https://avatars.githubusercontent.com/u/38628974?v=4","gravatar_id":"","url":"https://api.github.com/users/desmondlzy","html_url":"https://github.com/desmondlzy","followers_url":"https://api.github.com/users/desmondlzy/followers","following_url":"https://api.github.com/users/desmondlzy/following{/other_user}","gists_url":"https://api.github.com/users/desmondlzy/gists{/gist_id}","starred_url":"https://api.github.com/users/desmondlzy/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/desmondlzy/subscriptions","organizations_url":"https://api.github.com/users/desmondlzy/orgs","repos_url":"https://api.github.com/users/desmondlzy/repos","events_url":"https://api.github.com/users/desmondlzy/events{/privacy}","received_events_url":"https://api.github.com/users/desmondlzy/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2019-07-20T18:25:20Z","updated_at":"2019-10-17T07:24:48Z","closed_at":"2019-10-15T08:19:20Z","author_association":"NONE","active_lock_reason":null,"body":"I used some GPUs on the server to speed up training. But after downloading the trained model file to my PC (no GPU equipped) and run the `predict.py` script. It gives an error message related to `cuda_is_available()` , seems that the model trained on a GPU cannot predict on only-CPU machines? Is this an expected behavior? If not, any help will be appreciated! Thanks a lot!\r\n\r\nError Message:\r\n```\r\n(ml) C:\\Users\\lzy71\\MyProject\\character-based-cnn>python predict.py --model=./model/testmodel.pth --text=\"I love the pizza\" > msg.txt\r\nC:\\Users\\lzy71\\Anaconda3\\envs\\ml\\lib\\site-packages\\torch\\serialization.py:454: SourceChangeWarning: source code of class 'torch.nn.modules.container.ModuleList' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.\r\n  warnings.warn(msg, SourceChangeWarning)\r\nC:\\Users\\lzy71\\Anaconda3\\envs\\ml\\lib\\site-packages\\torch\\serialization.py:454: SourceChangeWarning: source code of class 'torch.nn.modules.container.Sequential' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.\r\n  warnings.warn(msg, SourceChangeWarning)\r\nC:\\Users\\lzy71\\Anaconda3\\envs\\ml\\lib\\site-packages\\torch\\serialization.py:454: SourceChangeWarning: source code of class 'torch.nn.modules.conv.Conv1d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.\r\n  warnings.warn(msg, SourceChangeWarning)\r\nTraceback (most recent call last):\r\n  File \"predict.py\", line 39, in <module>\r\n    prediction = predict(args)\r\n  File \"predict.py\", line 10, in predict\r\n    model = torch.load(args.model)\r\n  File \"C:\\Users\\lzy71\\Anaconda3\\envs\\ml\\lib\\site-packages\\torch\\serialization.py\", line 387, in load\r\n    return _load(f, map_location, pickle_module, **pickle_load_args)\r\n  File \"C:\\Users\\lzy71\\Anaconda3\\envs\\ml\\lib\\site-packages\\torch\\serialization.py\", line 574, in _load\r\n    result = unpickler.load()\r\n  File \"C:\\Users\\lzy71\\Anaconda3\\envs\\ml\\lib\\site-packages\\torch\\serialization.py\", line 537, in persistent_load\r\n    deserialized_objects[root_key] = restore_location(obj, location)\r\n  File \"C:\\Users\\lzy71\\Anaconda3\\envs\\ml\\lib\\site-packages\\torch\\serialization.py\", line 119, in default_restore_location\r\n    result = fn(storage, location)\r\n  File \"C:\\Users\\lzy71\\Anaconda3\\envs\\ml\\lib\\site-packages\\torch\\serialization.py\", line 95, in _cuda_deserialize\r\n    device = validate_cuda_device(location)\r\n  File \"C:\\Users\\lzy71\\Anaconda3\\envs\\ml\\lib\\site-packages\\torch\\serialization.py\", line 79, in validate_cuda_device\r\n    raise RuntimeError('Attempting to deserialize object on a CUDA '\r\nRuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location='cpu' to map your storages to the CPU.\r\n```","closed_by":{"login":"ahmedbesbes","id":6267065,"node_id":"MDQ6VXNlcjYyNjcwNjU=","avatar_url":"https://avatars.githubusercontent.com/u/6267065?v=4","gravatar_id":"","url":"https://api.github.com/users/ahmedbesbes","html_url":"https://github.com/ahmedbesbes","followers_url":"https://api.github.com/users/ahmedbesbes/followers","following_url":"https://api.github.com/users/ahmedbesbes/following{/other_user}","gists_url":"https://api.github.com/users/ahmedbesbes/gists{/gist_id}","starred_url":"https://api.github.com/users/ahmedbesbes/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/ahmedbesbes/subscriptions","organizations_url":"https://api.github.com/users/ahmedbesbes/orgs","repos_url":"https://api.github.com/users/ahmedbesbes/repos","events_url":"https://api.github.com/users/ahmedbesbes/events{/privacy}","received_events_url":"https://api.github.com/users/ahmedbesbes/received_events","type":"User","site_admin":false},"reactions":{"url":"https://api.github.com/repos/ahmedbesbes/character-based-cnn/issues/2/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/ahmedbesbes/character-based-cnn/issues/2/timeline","performed_via_github_app":null,"state_reason":"completed"}