{"url":"https://api.github.com/repos/mlflow/mlflow/issues/6273","repository_url":"https://api.github.com/repos/mlflow/mlflow","labels_url":"https://api.github.com/repos/mlflow/mlflow/issues/6273/labels{/name}","comments_url":"https://api.github.com/repos/mlflow/mlflow/issues/6273/comments","events_url":"https://api.github.com/repos/mlflow/mlflow/issues/6273/events","html_url":"https://github.com/mlflow/mlflow/issues/6273","id":1309845022,"node_id":"I_kwDOCB5Jx85OEqYe","number":6273,"title":"How to do model serve for unsupervised models?","user":{"login":"RavitejaBadugu","id":63113063,"node_id":"MDQ6VXNlcjYzMTEzMDYz","avatar_url":"https://avatars.githubusercontent.com/u/63113063?v=4","gravatar_id":"","url":"https://api.github.com/users/RavitejaBadugu","html_url":"https://github.com/RavitejaBadugu","followers_url":"https://api.github.com/users/RavitejaBadugu/followers","following_url":"https://api.github.com/users/RavitejaBadugu/following{/other_user}","gists_url":"https://api.github.com/users/RavitejaBadugu/gists{/gist_id}","starred_url":"https://api.github.com/users/RavitejaBadugu/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/RavitejaBadugu/subscriptions","organizations_url":"https://api.github.com/users/RavitejaBadugu/orgs","repos_url":"https://api.github.com/users/RavitejaBadugu/repos","events_url":"https://api.github.com/users/RavitejaBadugu/events{/privacy}","received_events_url":"https://api.github.com/users/RavitejaBadugu/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":3,"created_at":"2022-07-19T17:37:38Z","updated_at":"2022-07-23T08:59:49Z","closed_at":"2022-07-23T08:59:49Z","author_association":"NONE","active_lock_reason":null,"body":"I am using the code from [This URL. A basic example of using mlflow](https://github.com/RamVegiraju/mlflow-serving/blob/master/train.py).\r\nWhen I change the model and instead of using the supervised approach when I change it to unsupervised. (Just for checking how to use for unsupervised). The updated code is\r\n```\r\nimport pandas as pd\r\nimport numpy as np\r\nfrom sklearn.model_selection import train_test_split, cross_val_score\r\nfrom sklearn import datasets\r\nfrom sklearn.model_selection import train_test_split\r\nfrom sklearn.neighbors import NearestNeighbors\r\nimport mlflow\r\nimport mlflow.sklearn\r\n\r\nif __name__ == \"__main__\":\r\n    #Load data\r\n    boston = datasets.load_boston()\r\n    df = pd.DataFrame(boston.data, columns = boston.feature_names)\r\n    df['MEDV'] = boston.target\r\n    \r\n    #Split Model\r\n    X = df.drop(['MEDV'], axis = 1) \r\n    y = df['MEDV']\r\n    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .2, random_state = 42)\r\n    \r\n    #Model Creation\r\n    lm = NearestNeighbors()\r\n    lm.fit(X_train)\r\n    mlflow.sklearn.log_model(lm, \"model\")\r\n    print(\"Model saved in run %s\" % mlflow.active_run().info.run_uuid)\r\n```\r\nBut in artifacts MLmodel file is not having **python_function**\r\n```\r\nartifact_path: model\r\nflavors:\r\n  sklearn:\r\n    code: null\r\n    pickled_model: model.pkl\r\n    serialization_format: cloudpickle\r\n    sklearn_version: 1.1.1\r\nmlflow_version: 1.27.0\r\nmodel_uuid: cbb3594ef15f435da76e33a799879b87\r\nrun_id: f7eec4947499444db1903e7d609274e0\r\nutc_time_created: '2022-07-19 17:25:44.951115'\r\n```\r\nWhen I  run the command:\r\n```\r\nmlflow models serve --model-uri runs:/f7eec4947499444db1903e7d609274e0/model --no-conda\r\n```\r\nThe error I am getting is\r\n```\r\n`--env-manager=local` instead.\r\n  value = self.callback(ctx, self, value)\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\ravi1\\anaconda3\\envs\\restaurant\\lib\\runpy.py\", line 197, in _run_module_as_main\r\n    return _run_code(code, main_globals, None,\r\n  File \"C:\\Users\\ravi1\\anaconda3\\envs\\restaurant\\lib\\runpy.py\", line 87, in _run_code\r\n    exec(code, run_globals)\r\n  File \"C:\\Users\\ravi1\\anaconda3\\envs\\restaurant\\Scripts\\mlflow.exe\\__main__.py\", line 7, in <module>\r\n  File \"C:\\Users\\ravi1\\anaconda3\\envs\\restaurant\\lib\\site-packages\\click\\core.py\", line 1130, in __call__\r\n    return self.main(*args, **kwargs)\r\n  File \"C:\\Users\\ravi1\\anaconda3\\envs\\restaurant\\lib\\site-packages\\click\\core.py\", line 1055, in main\r\n    rv = self.invoke(ctx)\r\n  File \"C:\\Users\\ravi1\\anaconda3\\envs\\restaurant\\lib\\site-packages\\click\\core.py\", line 1657, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n  File \"C:\\Users\\ravi1\\anaconda3\\envs\\restaurant\\lib\\site-packages\\click\\core.py\", line 1657, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n  File \"C:\\Users\\ravi1\\anaconda3\\envs\\restaurant\\lib\\site-packages\\click\\core.py\", line 1404, in invoke\r\n    return ctx.invoke(self.callback, **ctx.params)\r\n  File \"C:\\Users\\ravi1\\anaconda3\\envs\\restaurant\\lib\\site-packages\\click\\core.py\", line 760, in invoke\r\n    return __callback(*args, **kwargs)\r\n  File \"C:\\Users\\ravi1\\anaconda3\\envs\\restaurant\\lib\\site-packages\\mlflow\\models\\cli.py\", line 68, in serve\r\n    return _get_flavor_backend(\r\n  File \"C:\\Users\\ravi1\\anaconda3\\envs\\restaurant\\lib\\site-packages\\mlflow\\models\\cli.py\", line 219, in _get_flavor_backend\r\n    raise Exception(\"No suitable flavor backend was found for the model.\")\r\nException: No suitable flavor backend was found for the model.\r\n```\r\nWhen I change it to supervised training. Everything is working fine.\r\nSo, how to use mlflow for unsupervised models?","closed_by":{"login":"harupy","id":17039389,"node_id":"MDQ6VXNlcjE3MDM5Mzg5","avatar_url":"https://avatars.githubusercontent.com/u/17039389?v=4","gravatar_id":"","url":"https://api.github.com/users/harupy","html_url":"https://github.com/harupy","followers_url":"https://api.github.com/users/harupy/followers","following_url":"https://api.github.com/users/harupy/following{/other_user}","gists_url":"https://api.github.com/users/harupy/gists{/gist_id}","starred_url":"https://api.github.com/users/harupy/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/harupy/subscriptions","organizations_url":"https://api.github.com/users/harupy/orgs","repos_url":"https://api.github.com/users/harupy/repos","events_url":"https://api.github.com/users/harupy/events{/privacy}","received_events_url":"https://api.github.com/users/harupy/received_events","type":"User","site_admin":false},"reactions":{"url":"https://api.github.com/repos/mlflow/mlflow/issues/6273/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/mlflow/mlflow/issues/6273/timeline","performed_via_github_app":null,"state_reason":"completed"}