{"url":"https://api.github.com/repos/mlflow/mlflow/issues/903","repository_url":"https://api.github.com/repos/mlflow/mlflow","labels_url":"https://api.github.com/repos/mlflow/mlflow/issues/903/labels{/name}","comments_url":"https://api.github.com/repos/mlflow/mlflow/issues/903/comments","events_url":"https://api.github.com/repos/mlflow/mlflow/issues/903/events","html_url":"https://github.com/mlflow/mlflow/issues/903","id":412090741,"node_id":"MDU6SXNzdWU0MTIwOTA3NDE=","number":903,"title":"REST API error with sklearn classifier","user":{"login":"mykelagrene","id":9121973,"node_id":"MDQ6VXNlcjkxMjE5NzM=","avatar_url":"https://avatars.githubusercontent.com/u/9121973?v=4","gravatar_id":"","url":"https://api.github.com/users/mykelagrene","html_url":"https://github.com/mykelagrene","followers_url":"https://api.github.com/users/mykelagrene/followers","following_url":"https://api.github.com/users/mykelagrene/following{/other_user}","gists_url":"https://api.github.com/users/mykelagrene/gists{/gist_id}","starred_url":"https://api.github.com/users/mykelagrene/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/mykelagrene/subscriptions","organizations_url":"https://api.github.com/users/mykelagrene/orgs","repos_url":"https://api.github.com/users/mykelagrene/repos","events_url":"https://api.github.com/users/mykelagrene/events{/privacy}","received_events_url":"https://api.github.com/users/mykelagrene/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2019-02-19T19:38:32Z","updated_at":"2019-03-05T02:18:41Z","closed_at":"2019-03-05T02:18:41Z","author_association":"NONE","active_lock_reason":null,"body":"### System information\r\n- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: I wrote a simple random forest classifier using sklearn and the iris dataset to test the mlflow workflow from scratch.\r\n- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 10.14.1\r\n- **MLflow installed from (source or binary)**: source (pip install mlflow)\r\n- **MLflow version (run ``mlflow --version``)**: 0.8.2\r\n- **Python version**: 3.7\r\n- **npm version (if running the dev UI):\r\n- **Exact command to reproduce**:curl -X POST -H \"Content-Type:application/json; format=pandas-split\" --data '{\"columns\":[\"sepal_length_cm\", \"sepal_width_cm\", \"petal_length_cm\", \"petal_width_cm\"],\"data\":[[5.3, 1.7, 3.5, 0.5]]}' http://127.0.0.1:1234/invocations\r\n\r\n### Describe the problem\r\nIf sklearn classifier.predict() method returns a categorical variable, then there is a 500 internal server error returned after the above http request.\r\n\r\nThe error is from the following function in mlflow/utils/__init.py__:\r\n\r\ndef ndarray2list(ndarray):\r\n    \"\"\"\r\n    Convert n-dimensional numpy array into nested lists and convert the elements types to native\r\n    python so that the list is json-able using standard json library.\r\n    :param ndarray: numpy array\r\n    :return: list representation of the numpy array with element types convereted to native python\r\n    \"\"\"\r\n    if len(ndarray.shape) <= 1:\r\n        return [x.item() for x in ndarray]\r\n    return [ndarray2list(ndarray[i, :]) for i in range(0, ndarray.shape[0])]\r\n\r\nx.item() fails if the array returned from the sklearn classifier.predict() method contains strings, as in the case of the iris dataset (labels are 'setosa', etc). I corrected the error on my local install by changing the function as below:\r\n\r\ndef ndarray2list(ndarray):\r\n    \"\"\"\r\n    Convert n-dimensional numpy array into nested lists and convert the elements types to native\r\n    python so that the list is json-able using standard json library.\r\n    :param ndarray: numpy array\r\n    :return: list representation of the numpy array with element types convereted to native python\r\n    \"\"\"\r\n    if len(ndarray.shape) <= 1:\r\n        try:\r\n            return [x.item() for x in ndarray]\r\n        except:\r\n            return [x for x in ndarray]\r\n    return [ndarray2list(ndarray[i, :]) for i in range(0, ndarray.shape[0])]\r\n\r\n### Source code / logs\r\nserver side error traceback:\r\n[2019-02-19 10:57:20,668] ERROR in app: Exception on /invocations [POST]\r\nTraceback (most recent call last):\r\n  File \"/anaconda3/lib/python3.7/site-packages/flask/app.py\", line 2292, in wsgi_app\r\n    response = self.full_dispatch_request()\r\n  File \"/anaconda3/lib/python3.7/site-packages/flask/app.py\", line 1815, in full_dispatch_request\r\n    rv = self.handle_user_exception(e)\r\n  File \"/anaconda3/lib/python3.7/site-packages/flask/app.py\", line 1718, in handle_user_exception\r\n    reraise(exc_type, exc_value, tb)\r\n  File \"/anaconda3/lib/python3.7/site-packages/flask/_compat.py\", line 35, in reraise\r\n    raise value\r\n  File \"/anaconda3/lib/python3.7/site-packages/flask/app.py\", line 1813, in full_dispatch_request\r\n    rv = self.dispatch_request()\r\n  File \"/anaconda3/lib/python3.7/site-packages/flask/app.py\", line 1799, in dispatch_request\r\n    return self.view_functions[rule.endpoint](**req.view_args)\r\n  File \"/anaconda3/lib/python3.7/site-packages/mlflow/server/handlers.py\", line 68, in wrapper\r\n    return func(*args, **kwargs)\r\n  File \"/anaconda3/lib/python3.7/site-packages/mlflow/pyfunc/scoring_server.py\", line 185, in transformation\r\n    predictions = get_jsonable_obj(raw_predictions, pandas_orient=\"records\")\r\n  File \"/anaconda3/lib/python3.7/site-packages/mlflow/utils/__init__.py\", line 34, in get_jsonable_obj\r\n    return ndarray2list(data)\r\n  File \"/anaconda3/lib/python3.7/site-packages/mlflow/utils/__init__.py\", line 20, in ndarray2list\r\n    return [x.item() for x in ndarray]\r\n  File \"/anaconda3/lib/python3.7/site-packages/mlflow/utils/__init__.py\", line 20, in <listcomp>\r\n    return [x.item() for x in ndarray]\r\nAttributeError: 'str' object has no attribute 'item'","closed_by":{"login":"tomasatdatabricks","id":33237569,"node_id":"MDQ6VXNlcjMzMjM3NTY5","avatar_url":"https://avatars.githubusercontent.com/u/33237569?v=4","gravatar_id":"","url":"https://api.github.com/users/tomasatdatabricks","html_url":"https://github.com/tomasatdatabricks","followers_url":"https://api.github.com/users/tomasatdatabricks/followers","following_url":"https://api.github.com/users/tomasatdatabricks/following{/other_user}","gists_url":"https://api.github.com/users/tomasatdatabricks/gists{/gist_id}","starred_url":"https://api.github.com/users/tomasatdatabricks/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/tomasatdatabricks/subscriptions","organizations_url":"https://api.github.com/users/tomasatdatabricks/orgs","repos_url":"https://api.github.com/users/tomasatdatabricks/repos","events_url":"https://api.github.com/users/tomasatdatabricks/events{/privacy}","received_events_url":"https://api.github.com/users/tomasatdatabricks/received_events","type":"User","site_admin":false},"reactions":{"url":"https://api.github.com/repos/mlflow/mlflow/issues/903/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/mlflow/mlflow/issues/903/timeline","performed_via_github_app":null,"state_reason":"completed"}