{"url":"https://api.github.com/repos/sacmehta/ESPNetv2/issues/4","repository_url":"https://api.github.com/repos/sacmehta/ESPNetv2","labels_url":"https://api.github.com/repos/sacmehta/ESPNetv2/issues/4/labels{/name}","comments_url":"https://api.github.com/repos/sacmehta/ESPNetv2/issues/4/comments","events_url":"https://api.github.com/repos/sacmehta/ESPNetv2/issues/4/events","html_url":"https://github.com/sacmehta/ESPNetv2/issues/4","id":389167913,"node_id":"MDU6SXNzdWUzODkxNjc5MTM=","number":4,"title":"RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/aten/src/THC/generic/THCTensorCopy.cpp:70","user":{"login":"monk42","id":33028017,"node_id":"MDQ6VXNlcjMzMDI4MDE3","avatar_url":"https://avatars.githubusercontent.com/u/33028017?v=4","gravatar_id":"","url":"https://api.github.com/users/monk42","html_url":"https://github.com/monk42","followers_url":"https://api.github.com/users/monk42/followers","following_url":"https://api.github.com/users/monk42/following{/other_user}","gists_url":"https://api.github.com/users/monk42/gists{/gist_id}","starred_url":"https://api.github.com/users/monk42/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/monk42/subscriptions","organizations_url":"https://api.github.com/users/monk42/orgs","repos_url":"https://api.github.com/users/monk42/repos","events_url":"https://api.github.com/users/monk42/events{/privacy}","received_events_url":"https://api.github.com/users/monk42/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":12,"created_at":"2018-12-10T07:11:31Z","updated_at":"2019-01-11T05:26:46Z","closed_at":"2019-01-11T05:26:46Z","author_association":"NONE","active_lock_reason":null,"body":"When I run the segmentation codes , i got this error!  \r\n![59fdee984bae45d85735b2e52b0e8b5](https://user-images.githubusercontent.com/33028017/49715975-308dfc80-fc8d-11e8-8a30-61f31f4cda25.png)\r\n\r\nIt seems that there is a problem in calculating the loss functionÔºÅThe loss value cannot be calculated.\r\n\r\nI run this codes in pytorch0.4.1 and python3 and opencv 3.2.0\r\n\r\n \r\n","closed_by":{"login":"sacmehta","id":18603245,"node_id":"MDQ6VXNlcjE4NjAzMjQ1","avatar_url":"https://avatars.githubusercontent.com/u/18603245?v=4","gravatar_id":"","url":"https://api.github.com/users/sacmehta","html_url":"https://github.com/sacmehta","followers_url":"https://api.github.com/users/sacmehta/followers","following_url":"https://api.github.com/users/sacmehta/following{/other_user}","gists_url":"https://api.github.com/users/sacmehta/gists{/gist_id}","starred_url":"https://api.github.com/users/sacmehta/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/sacmehta/subscriptions","organizations_url":"https://api.github.com/users/sacmehta/orgs","repos_url":"https://api.github.com/users/sacmehta/repos","events_url":"https://api.github.com/users/sacmehta/events{/privacy}","received_events_url":"https://api.github.com/users/sacmehta/received_events","type":"User","site_admin":false},"reactions":{"url":"https://api.github.com/repos/sacmehta/ESPNetv2/issues/4/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/sacmehta/ESPNetv2/issues/4/timeline","performed_via_github_app":null,"state_reason":"completed"}