{"url":"https://api.github.com/repos/aiqm/torchani/issues/195","repository_url":"https://api.github.com/repos/aiqm/torchani","labels_url":"https://api.github.com/repos/aiqm/torchani/issues/195/labels{/name}","comments_url":"https://api.github.com/repos/aiqm/torchani/issues/195/comments","events_url":"https://api.github.com/repos/aiqm/torchani/issues/195/events","html_url":"https://github.com/aiqm/torchani/issues/195","id":424229202,"node_id":"MDU6SXNzdWU0MjQyMjkyMDI=","number":195,"title":"image not found","user":{"login":"Gvinkc","id":36750978,"node_id":"MDQ6VXNlcjM2NzUwOTc4","avatar_url":"https://avatars.githubusercontent.com/u/36750978?v=4","gravatar_id":"","url":"https://api.github.com/users/Gvinkc","html_url":"https://github.com/Gvinkc","followers_url":"https://api.github.com/users/Gvinkc/followers","following_url":"https://api.github.com/users/Gvinkc/following{/other_user}","gists_url":"https://api.github.com/users/Gvinkc/gists{/gist_id}","starred_url":"https://api.github.com/users/Gvinkc/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/Gvinkc/subscriptions","organizations_url":"https://api.github.com/users/Gvinkc/orgs","repos_url":"https://api.github.com/users/Gvinkc/repos","events_url":"https://api.github.com/users/Gvinkc/events{/privacy}","received_events_url":"https://api.github.com/users/Gvinkc/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":3,"created_at":"2019-03-22T14:12:50Z","updated_at":"2019-03-23T06:27:34Z","closed_at":"2019-03-23T06:27:34Z","author_association":"NONE","active_lock_reason":null,"body":"Hi, I am trying to run in macbook pro. Could you please help on the following error?\r\nTraceback (most recent call last):\r\n  File \"energy_force.py\", line 13, in <module>\r\n    import torch\r\n  File \"/anaconda3/envs/py36/lib/python3.6/site-packages/torch/__init__.py\", line 79, in <module>\r\n    from torch._C import *\r\nImportError: dlopen(/anaconda3/envs/py36/lib/python3.6/site-packages/torch/_C.cpython-36m-darwin.so, 9): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib\r\n  Referenced from: /anaconda3/envs/py36/lib/python3.6/site-packages/torch/lib/libshm.dylib\r\n  Reason: image not found\r\n","closed_by":{"login":"zasdfgbnm","id":1032377,"node_id":"MDQ6VXNlcjEwMzIzNzc=","avatar_url":"https://avatars.githubusercontent.com/u/1032377?v=4","gravatar_id":"","url":"https://api.github.com/users/zasdfgbnm","html_url":"https://github.com/zasdfgbnm","followers_url":"https://api.github.com/users/zasdfgbnm/followers","following_url":"https://api.github.com/users/zasdfgbnm/following{/other_user}","gists_url":"https://api.github.com/users/zasdfgbnm/gists{/gist_id}","starred_url":"https://api.github.com/users/zasdfgbnm/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/zasdfgbnm/subscriptions","organizations_url":"https://api.github.com/users/zasdfgbnm/orgs","repos_url":"https://api.github.com/users/zasdfgbnm/repos","events_url":"https://api.github.com/users/zasdfgbnm/events{/privacy}","received_events_url":"https://api.github.com/users/zasdfgbnm/received_events","type":"User","site_admin":false},"reactions":{"url":"https://api.github.com/repos/aiqm/torchani/issues/195/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/aiqm/torchani/issues/195/timeline","performed_via_github_app":null,"state_reason":"completed"}